---
title: 'Class 6: R Functions'
author: "Rose Li"
date: "4/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview 
Today we will focus on **R functions** but we weill start with a bit of **file reading**.
```{r}
plot(1:10, type="l", col="blue")
```


```{r}
read.table("test1.txt", header = TRUE, sep=",")
```

```{r}
read.table("test2.txt", header = TRUE, sep="$")
```

```{r}
read.table("test3.txt")
```

## Our First Function

Add some numbers
```{r}
add <- function(x, y=1) {
  #The body 
  x+y
}
```

```{r}
add(4)
```

```{r}
add(4,5)
```

```{r}
add(x=4,y=5)
```

```{r}
add(c(1,3,5),1)
```

```{r}
add(c(1,3,5))
```

```{r}
#add(x=1, y="rose") **error**
```

```{r}
#add(1,3,5) **error**
```

## Our 2nd exmaple function
```{r}
rescale <- function(x) {
rng <-range(x)
(x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale(c(1,3,NA,5,10))
```


```{r}
rescale( 1:10 )
```

```{r}
x <- c(1,3,NA,5,10)
rng <-range(x, na.rm=TRUE)
rng
(x - rng[1]) / (rng[2] - rng[1])
```

```{r}
rescale2 <- function(x) {
rng <-range(x, na.rm=TRUE)
(x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale2 <- function(x, na.rm=TRUE) {
rng <-range(x, na.rm=na.rm)
(x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale2(c(1,3,NA,10))
```

Another exmample extension 
```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
if(na.rm) {
rng <-range(x, na.rm=na.rm)
} else {
rng <-range(x)
}
print("Hello")
answer <- (x - rng[1]) / (rng[2] - rng[1])
print("is it me you are looking for?")
if(plot) {
plot(answer, typ="b", lwd=4)
  print("Don't Sing Please!")
}
print("I can see it in ...")
return(answer)
}
```

```{r}
rescale3(1:10)
```

```{r}
rescale3(1:10, plot=TRUE)
```



